<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <title>TestForm {$title}</title>
                <link rel="stylesheet" type="text/css" href="css/mini.css" media="all">
                    
                <script type="text/javascript" src="js/mini.js"></script>
                <script src="http://code.jquery.com/jquery-1.7.2.js"></script>
                <script src="js/main.js"></script>
    </head>
    <body id="main_body" >

                    <div class="done">
                    <b>Vielen Dank. Wir haben Ihre Anfrage erhalten</b>
                    </div>
                    
                    <img id="top" src="http://nb.einsclone.lo/miniproject/statics/top.png" alt="">
                    
                        <div id="form_container">

                    
                            
                            <form id="miniform" class="appnitro"  method="post" action="#">
                                <div class="form_description">
                                    <h2>TestForm {$name}</h2><div class="loading_icon"></div>
                                    <p>This is your form description. Click here to edit.</p>
                                </div>						
                                <ul >

                                    <li id="li_1" >
                                        <label class="description" for="element_1">name </label>
                                        <div>
                                            <input id="name" name="name" class="element text medium" type="text" maxlength="255" value=""/> 
                                        </div><p class="guidelines" id="guide_1"><small>Type your name</small></p> 
                                    </li>		
                                    <li id="li_4" >
                                        <label class="description" for="checkit">Checkboxes </label>
                                        <span>
                                            <input id="checkit_1" name="checkit_1" class="element checkbox" type="checkbox" value="1" />
                                            <label class="choice" for="checkit_1">First option</label>
                                            <input id="checkit_2" name="checkit_2" class="element checkbox" type="checkbox" value="1" />
                                            <label class="choice" for="checkit_2">Second option</label>
                                            <input id="checkit_3" name="checkit_3" class="element checkbox" type="checkbox" value="1" />
                                            <label class="choice" for="checkit_3">Third option</label>

                                        </span> 
                                    </li>		
                                    <li id="li_3" >
                                        <label class="description" for="textfieldbig">Paragraph </label>
                                        <div>
                                            <textarea id="textfieldbig" name="textfieldbig" class="element textarea medium"></textarea> 
                                        </div> 
                                    </li>		
                                    <li id="li_5" >
                                        <label class="description" for="weather">Check your weather </label>
                                        <span>
                                            <input id="weather_1" name="weather" class="element radio" type="radio" value="water" />
                                            <label class="choice" for="weather_1">rain</label>
                                            <input id="weather_2" name="weather" class="element radio" type="radio" value="air" />
                                            <label class="choice" for="weather_2">sun</label>
                                            <input id="weather_3" name="weather" class="element radio" type="radio" value="snow" />
                                            <label class="choice" for="weather_3">snow</label>

                                        </span><p class="guidelines" id="guide_5"><small>type in your weather wish</small></p> 
                                    </li>

                                    <li class="buttons">
                                        <input type="hidden" name="form_id" value="450264" />

                                        <input id="submit" class="button_text" type="submit" name="submit" value="Submit" />
                                    </li>
                                </ul>
                            </form>	
                            <div id="footer">
                                Generated by <a href="http://www.phpform.org">pForm</a>
                            </div>
                        </div>
<img id="bottom" src="http://nb.einsclone.lo/miniproject/statics/bottom.png" alt="">
</body>
</html>